coding_task:
  description: >
    Find out what whether to use python or pyspark for this assignment: {assignment}
    Always check the assignment and then decide whether to use python or pyspark.
    Then write the python or pyspark (whichever is chosen) code for this assignment: {assignment}
  expected_output: >
    The python or pyspark (whichever is chosen) code for this assignment: {assignment}
    solution document file which explains how to use, run and test the solution with an example.
  agent: coding_agent
  output_file: output/solution.md
